---
- name: Ensure all packages are up to date
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: yes

- name: Check if a reboot is needed
  ansible.builtin.shell: |
    if [ -f /var/run/reboot-required ]; then
      echo "reboot needed"
    fi
  register: reboot_required
  changed_when: reboot_required.stdout != ""

- name: Reboot the server if needed
  ansible.builtin.reboot:
  when: reboot_required.stdout != ""
